import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import {
  faFacebook,
  faInstagram,
  faTwitter,
  faLinkedin,
  faSpotify,
  faGithub,
  faHackerrank,
  faMedium,
  faDev,
  faPinterest,
  faBehance,
  faDribbble,
  faCodepen,
} from "@fortawesome/free-brands-svg-icons"
import { faSail } from "@fortawesome/free-brands-svg-icons"

export const GitHubConfig = {
  username: "PurinatG-01",
  icon: () => <FontAwesomeIcon icon={faGithub} />,
}

const typeColorScheme = {
  dev: "var(--reverse-bg)",
  social: "var(--base-green)",
  blog: "var(--base-blue)",
  design: "var(--base-yellow)",
}

export default [
  {
    title: "Github",
    url: "https://github.com/PurinatG-01",
    description: "PurinatG-01",
    icon: () => <FontAwesomeIcon icon={faGithub} />,
    active: true,
    type: 'dev',
    typeColor: typeColorScheme.dev,
  },
  {
    title: "Spotify",
    url: "https://open.spotify.com/user/214rbqcrsqoigzjlq3oiem4ry",
    description: "Fame Sanbundit",
    icon: () => <FontAwesomeIcon icon={faSpotify} />,
    active: true,
    type: 'social',
    typeColor: typeColorScheme.social,
  },
  {
    title: "Instagram",
    url: "https://www.instagram.com/chofongsua/",
    description: "@chofongsua",
    icon: () => <FontAwesomeIcon icon={faInstagram} />,
    active: true,
    type: 'social',
    typeColor: typeColorScheme.social,
  },
  {
    title: "Pinterest",
    url: "https://www.pinterest.com/fame3js49/_saved/",
    description: "Purinat Sanbundit",
    icon: () => <FontAwesomeIcon icon={faPinterest} />,
    active: true,
    type: 'design',
    typeColor: typeColorScheme.design,
  },
  {
    title: "HackkerRank",
    url: "https://www.hackerrank.com/fame3js49",
    description: "Purinat Sanbundit",
    icon: () => <FontAwesomeIcon icon={faHackerrank} />,
    type: 'dev',
    typeColor: typeColorScheme.dev,
  },
  {
    title: "Medium",
    url: "https://medium.com/@fame3js49",
    description: "chofongsua",
    icon: () => <FontAwesomeIcon icon={faMedium} />,
    type: 'blog',
    typeColor: typeColorScheme.blog,
  },
  {
    title: "Codepen",
    url: "https://codepen.io/hobostep",
    description: "@Hobostep",
    icon: () => <FontAwesomeIcon icon={faCodepen} />,
    type: 'dev',
    typeColor: typeColorScheme.dev,
  },
  {
    title: "Dev.to",
    url: "https://dev.to/purinatg01",
    description: "@purinatg01",
    icon: () => <FontAwesomeIcon icon={faDev} />,
    type: 'blog',
    typeColor: typeColorScheme.blog,
  },
  {
    title: "LinkedIn",
    url: "https://www.linkedin.com/in/purinat-sanbundit-12266217a/",
    description: "Purinat Sanbundit",
    icon: () => <FontAwesomeIcon icon={faLinkedin} />,
    type: 'social',
    typeColor: typeColorScheme.social,
  },
  {
    title: "Behance",
    url: "https://www.behance.net/5574b503",
    description: "Purinat Sanbundit",
    icon: () => <FontAwesomeIcon icon={faBehance} />,
    type: 'design',
    typeColor: typeColorScheme.design,
  },
  {
    title: "Dribbble",
    url: "https://dribbble.com/chofongsua",
    description: "chofongsua | Purinat Sanbundit",
    icon: () => <FontAwesomeIcon icon={faDribbble} />,
    type: 'design',
    typeColor: typeColorScheme.design,
  },
  {
    title: "Opensea",
    url: "https://opensea.io/chopatra",
    description: "chopatra by chofongsua",
    icon: () => <FontAwesomeIcon icon="fa-solid fa-sailboat" />,
    type: 'social',
    typeColor: typeColorScheme.social,
  },
  {
    title: "Facebook",
    url: "https://www.facebook.com/purinat.sanbundit/",
    description: "Fame Sanbundit",
    icon: () => <FontAwesomeIcon icon={faFacebook} />,
    type: 'social',
    typeColor: typeColorScheme.social,
  },
  {
    title: "Twitter",
    url: "https://twitter.com/pemaf1",
    description: "@pemaf1",
    icon: () => <FontAwesomeIcon icon={faTwitter} />,
    type: 'social',
    typeColor: typeColorScheme.social,
  },
]
